on:
  push:
    branches:
      - bitacora
    paths:
      - 'docs/lexuniversalis/**'   # opcional pero recomendado
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: docs/lexuniversalis   # <- ESTA RUTA
          api_location: ''                    # <- vacío
          output_location: ''                 # <- vacío (no pongas '.')
