name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
    # opcional:
    # paths:
    #   - '**/*.html'
    #   - '**/*.css'
    #   - '**/*.js'
    #   - 'staticwebapp.config.json'
    #   - 'CNAME'
  workflow_dispatch: {}

# opcional: evita despliegues simultáneos
concurrency:
  group: swa-prod
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_PEBBLE_022FAE910 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          api_location: ""
          output_location: "."
          skip_app_build: true
          production_branch: "main"
